// Generates contracts/libraries/SMTDefaults.sol: the precomputed empty-subtree hashes.
// default[0] = empty leaf = 0x00..00; default[i+1] = keccak256(default[i] ++ default[i]).
// Run: npx ts-node scripts/gen-smt-defaults.ts   (output is committed; never recomputed on-chain)
import { keccak256, concat, ZeroHash } from "ethers";
import * as fs from "fs";
import * as path from "path";

const DEPTH = 256;
const d: string[] = [ZeroHash];
for (let i = 0; i < DEPTH; i++) d.push(keccak256(concat([d[i], d[i]])));

const hex = d.map((h) => h.slice(2)).join("");
const out = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice GENERATED by scripts/gen-smt-defaults.ts - do not edit by hand.
/// @dev Packed empty-subtree hashes: entry i (bytes [32*i, 32*i+32)) is the root of an all-empty
///      subtree of height i, for i in [0, 256]. Entry 0 is the empty leaf (0x00..00); entry 256 is
///      the root of a completely empty tree (${d[DEPTH]}).
///      hash(node) = keccak256(left || right), no domain prefix.
library SMTDefaults {
    bytes32 internal constant EMPTY_ROOT = ${d[DEPTH]};

    bytes internal constant DEFAULTS =
        hex"${hex}";
}
`;
fs.writeFileSync(path.join(__dirname, "..", "contracts", "libraries", "SMTDefaults.sol"), out);
console.log("empty root:", d[DEPTH]);
